kind: Deployment
apiVersion: apps/v1
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: dregistry.xaasfarm.com/xaasfarm/xaasfarm/cc_backend-auth:Development
          imagePullPolicy: Always

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: import
spec:
  selector:
    matchLabels:
      app: import
  replicas: 1
  template:
    metadata:
      labels:
        app: import
    spec:
      containers:
        - name: import
          image: dregistry.xaasfarm.com/xaasfarm/xaasfarm/cc_backend-import:Development
          imagePullPolicy: Always

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: issue
spec:
  selector:
    matchLabels:
      app: issue
  replicas: 1
  template:
    metadata:
      labels:
        app: issue
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: mongodb+srv://dbUser1:2ym5a8aBl95VmchG@cluster0.edcw5.mongodb.net/admin?replicaSet=atlas-paxjaq-shard-0&readPreference=primary&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
          name: issue
          image: dregistry.xaasfarm.com/xaasfarm/xaasfarm/cc_backend-issue:Development
          imagePullPolicy: Always

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: dregistry.xaasfarm.com/xaasfarm/xaasfarm/cc_backend:Development
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cloudclip-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.cloudclip.de`)
      kind: Rule
      services:
        - name: gateway
          port: 80
