const OutlookCategoryPresetColors = {
  PRESET_0: 'preset0',
  PRESET_1: 'preset1',
  PRESET_2: 'preset2',
  PRESET_3: 'preset3',
  PRESET_4: 'preset4',
  PRESET_5: 'preset5',
  PRESET_6: 'preset6',
  PRESET_7: 'preset7',
  PRESET_8: 'preset8',
  PRESET_9: 'preset9',
  PRESET_10: 'preset10',
  PRESET_11: 'preset11',
  PRESET_12: 'preset12',
  PRESET_13: 'preset13',
  PRESET_14: 'preset14',
  PRESET_15: 'preset15',
  PRESET_16: 'preset16',
  PRESET_17: 'preset17',
  PRESET_18: 'preset18',
  PRESET_19: 'preset19',
  PRESET_20: 'preset20',
  PRESET_21: 'preset21',
  PRESET_22: 'preset22',
  PRESET_23: 'preset23',
  PRESET_24: 'preset24',
}

const OutlookCategoryColors = {
  [OutlookCategoryPresetColors.PRESET_0]: '#E74856',
  [OutlookCategoryPresetColors.PRESET_1]: '#FF8C00',
  [OutlookCategoryPresetColors.PRESET_2]: '#FFAB45',
  [OutlookCategoryPresetColors.PRESET_3]: '#FFF100',
  [OutlookCategoryPresetColors.PRESET_4]: '#47D041',
  [OutlookCategoryPresetColors.PRESET_5]: '#30C6CC',
  [OutlookCategoryPresetColors.PRESET_6]: '#73AA24',
  [OutlookCategoryPresetColors.PRESET_7]: '#00BCF2',
  [OutlookCategoryPresetColors.PRESET_8]: '#8764B8',
  [OutlookCategoryPresetColors.PRESET_9]: '#F495BF',
  [OutlookCategoryPresetColors.PRESET_10]: '#A0AEB2',
  [OutlookCategoryPresetColors.PRESET_11]: '#004B60',
  [OutlookCategoryPresetColors.PRESET_12]: '#B1ADAB',
  [OutlookCategoryPresetColors.PRESET_13]: '#5D5A58',
  [OutlookCategoryPresetColors.PRESET_14]: '#000000',
  [OutlookCategoryPresetColors.PRESET_15]: '#750B1C',
  [OutlookCategoryPresetColors.PRESET_16]: '#CA5010',
  [OutlookCategoryPresetColors.PRESET_17]: '#AB620D',
  [OutlookCategoryPresetColors.PRESET_18]: '#C19C00',
  [OutlookCategoryPresetColors.PRESET_19]: '#004B1C',
  [OutlookCategoryPresetColors.PRESET_20]: '#004B50',
  [OutlookCategoryPresetColors.PRESET_21]: '#0B6A0B',
  [OutlookCategoryPresetColors.PRESET_22]: '#002050',
  [OutlookCategoryPresetColors.PRESET_23]: '#32145A',
  [OutlookCategoryPresetColors.PRESET_24]: '#5C005C',
}

const OutlookCategoryPresetColorsArray = [
  OutlookCategoryPresetColors.PRESET_0,
  OutlookCategoryPresetColors.PRESET_1,
  OutlookCategoryPresetColors.PRESET_2,
  OutlookCategoryPresetColors.PRESET_3,
  OutlookCategoryPresetColors.PRESET_4,
  OutlookCategoryPresetColors.PRESET_5,
  OutlookCategoryPresetColors.PRESET_6,
  OutlookCategoryPresetColors.PRESET_7,
  OutlookCategoryPresetColors.PRESET_8,
  OutlookCategoryPresetColors.PRESET_9,
  OutlookCategoryPresetColors.PRESET_10,
  OutlookCategoryPresetColors.PRESET_11,
  OutlookCategoryPresetColors.PRESET_12,
  OutlookCategoryPresetColors.PRESET_13,
  OutlookCategoryPresetColors.PRESET_14,
  OutlookCategoryPresetColors.PRESET_15,
  OutlookCategoryPresetColors.PRESET_16,
  OutlookCategoryPresetColors.PRESET_17,
  OutlookCategoryPresetColors.PRESET_18,
  OutlookCategoryPresetColors.PRESET_19,
  OutlookCategoryPresetColors.PRESET_20,
  OutlookCategoryPresetColors.PRESET_21,
  OutlookCategoryPresetColors.PRESET_22,
  OutlookCategoryPresetColors.PRESET_23,
  OutlookCategoryPresetColors.PRESET_24,
]

const CategoryOrigin = {
  OUTLOOK: 'outlook',
  CUSTOM_FIELDS: 'custom_fields',
  EVENT_CATEGORIES: 'event_categories',
}

module.exports = {
  CategoryOrigin,
  OutlookCategoryPresetColors,
  OutlookCategoryColors,
  OutlookCategoryPresetColorsArray,
}
